return {
    require("plugins.vimtex"),
    require("plugins.autopairs"),
    require("plugins.diffview"),
    require("plugins.colorizer"),
    require("plugins.comment"),
    require("plugins.conform"),
    require("plugins.colors"),
    require("plugins.cp"),
    require("plugins.dashboard"),
    -- require("plugins.everforest"),
    require("plugins.nightfox"),
    require("plugins.lualine"),
    require("plugins.debug"),
    require("plugins.neogit"),
    require("plugins.tailwindcss-colorizer-cmp"),
    require("plugins.telescope"),
    require("plugins.treesitter"),
    require("plugins.true-zen"),
    require("plugins.neogit"),
    require("plugins.lspzero"),
    require("plugins.ultisnip"),
    require("plugins.markdown"),
}
